### ISSUE TITLE
Deleting input's contents allows all characters

### ISSUE THREAD

**Issue by alex-dixon** [imcnally/react-currency-masked-input#1]
Hey! Great work.

It appears that selecting all characters and deleting them allows the input of any character. :(

I'm not sure how to fix it otherwise I would submit a pull request.

**Comment by imcnally** [comment]
Hey Alex! I'm flattered to get my first issue, so thanks.

To disallow the input of any character, on `<CurrencyMaskedInput>`, put a pattern like you would on an input:

```html
<CurrencyMaskedInput pattern="\d+">
```

This will only allow numbers to be input. 

I'll have to think about putting that into the source code, but I'm more in favor of being as light touch as possible, and allowing the user of CurrencyMaskedInput to choose what they want the pattern to be. Accordingly, I'll be closing your PR. But again, thanks!

**Comment by alex-dixon** [comment]
Welcome to open source software! :smile: 

I just tried your suggestion in my code and it didn't work for me. The PR I submitted fixed the issue on my end. I forgot to mention I was also able to type in a letter after focusing on the input the first time. The change in the PR I submitted fixes that as well. Thanks!

**Comment by imcnally** [comment]
There doesn't seem to be a way, with HTML, to ensure on digits are input. That's sad. Even with `pattern` and `min`. I also don't want this library to get into the game of ensuring input either. That can be done by the user, if its important to them.

As far as your use case, I don't necessarily want `return '0'` to be the default for bad input. But! It could make sense to return the defaultValue prop. In your case, it'd be `<CurrencyMaskedInput defaultValue='0' />` and you could make your change into:

```jsx
if (!digits.length) { return this.props.defaultValue || null }
```

**Comment by imcnally** [comment]
Hey @alex-dixon, I just pushed v 0.0.9. that returns a zero when invalid input is received. I should have listened to you!

I realized my reservation was having the ability to clear the input, and it's harder than I thought. In both events, clearing the input, or putting in non-digits, the event.target.value is `''`. Turns out the event also includes a [validity](https://html.spec.whatwg.org/#dom-cva-validity) object. On non-digit input, `event.target.validity.badInput` is true. On a cleared input, it is false.

Thanks for contributing, and I hope you can make use of the project again!
